### ISSUE TITLE
Measure PoR

### ISSUE THREAD

**Issue by emizzle** [status-im/codex-research#111]
Check consistency with Leo's simulations.

**Comment by cskiraly** [comment]
# old results (with parameters selected ad-hoc)

#### M1 native ARM, NVMe SSD
```
CPU Time [Key generation] 0.001s
File size=10485760 bytes, blocks=331, sectors/block=1024, sectorsize=31 bytes
CPU Time [Auth generation] 26.805s
CPU Time [Generating challenge...] 0.000s
CPU Time [Issuing proof...] 0.022s
CPU Time [Verifying proof...] 0.085s
```

#### laptop with a i7-10750H
```
File size=26999910 bytes, blocks=851, sectors/block=1024, sectorsize=31 bytes
CPU Time [Auth generation] 150.004s
CPU Time [Generating challenge...] 0.000s
CPU Time [Issuing proof...] 0.036s
CPU Time [Verifying proof...] 0.185s
```

#### GMK Nucbox (Intel Celeron J4125 CPU @ 2.00GHz + 8GB RAM) 
```
./env.sh nim c -r -d:danger dagger/por/testpor.nim 
[...]
CPU Time [Key generation] 0.002s
File size=104780000 bytes, blocks=3301, sectors/block=1024, sectorsize=31 bytes
CPU Time [Auth generation (s=1024)] 5.659s
CPU Time [Generating challenge (q=22)] 0.008s
CPU Time [Issuing proof] 0.049s
CPU Time [Verifying proof] 0.335s
Result: true
```

**Comment by cskiraly** [comment]
some results and instructions are in https://hackmd.io/3Dj3J70DQPi9c-WaWX97gw
@leobago

**Comment by leobago** [comment]
Looking at the old data, here is how I understand these results:

**M1 native ARM, NVMe SSD**
`File size=10485760 bytes (10MB), blocks=331, sectors/block=1024, sectorsize=31 bytes`
Issuing proof takes 0.022s/PoR-block, so 7.2 seconds for the entire file if it was stored on one single node. This is an average of 21.4 microseconds per PoR sector.

**laptop with a i7-10750H**
`File size=26999910 bytes (25MB), blocks=851, sectors/block=1024, sectorsize=31 bytes`
Issuing proof takes 0.036s/PoR-block, so 30.6 seconds for the entire file if it was stored on one single node. This is an average of 35.1 microseconds per PoR sector.

**GMK Nucbox (Intel Celeron J4125 CPU @ 2.00GHz + 8GB RAM)**
`File size=104780000 bytes (100MB), blocks=3301, sectors/block=1024, sectorsize=31 bytes`
Issuing proof takes 0.049s/PoR-block, so 161.7 seconds for the entire file if it was stored on one single node. This is an average of 47.8 microseconds per PoR sector.

Is this a correct understanding?

**Comment by cskiraly** [comment]
> Looking at the old data, here is how I understand these results:
> 
> **M1 native ARM, NVMe SSD** `File size=10485760 bytes (10MB), blocks=331, sectors/block=1024, sectorsize=31 bytes` Issuing proof takes 0.022s/PoR-block, so 7.2 seconds for the entire file if it was stored on one single node. This is an average of 21.4 microseconds per PoR sector.
> [...]
> 
> Is this a correct understanding?

Looking at this again, I see only now that the q (challenge size) parameter was not part of your calculations. It was actually exposed in the logs of only the last result, where q=22.  I think it was 22 also earlier, but I'm not sure. Q is exposed in the new results, which I'm copying here next.

**Comment by cskiraly** [comment]
# PoR speed comparison

## theoretic speed and scalability (number of ops)

See also in https://github.com/status-im/nim-codex/blob/5aa42541b3634e0f168e88780c64ad181590cc1f/codex/storageproofs/por/por.nim#L44-L79

The following table summarizes the number of operations in different phases using the following notation:
 - $f$: file size expressed in units of 31 bytes
 - $n$: number of blocks
 - $s$: number of sectors per block
 - $q$: number of query items

Since $f = n * s$ and $s$ is a parameter of the scheme, it is better to express
the cost as a function of $f$ and $s$. This only matters for Setup, all other
phases are independent of the file size assuming a given $q$.

|                |         Setup             | Challenge |   Proof   | Verify    |
|----------------|---------------------------|-----------|-----------|-----------|
| G1 random      | $s         = s$             | $q$         |           |           |
| G1 scalar mult | $n * (s+1) = f * (1 + 1/s)$ |           | $q$         | $q + s$     |
| G1 add         | $n * s     = f$             |           | $q-1$       | $q-1 + s-1$ |
| Hash to G1     | $n         = f / s$         |           |           | $q$         |
| $Z_p$ mult       |                           |           | $s * q$     |           |
| $Z_p$ add        |                           |           | $s * (q-1)$ |           |
| pairing        |                           |           |           | 2         |

### Storage and communication cost
The **storage overhead** for a file of $f_b$ bytes is given by the $n$ authenticators
calculated in the setup phase.
  $$f_b = f * 31 = n * s * 31$$
Each authenticator is a point on $G_1$, which occupies 48 bytes in compressed form.
Thus, the overall storage size in bytes is:
  $$f_{pos} = f_b + n * 48 = f_b * (1 + (48/31) * (1/s))$$

**Communication cost** in the Setup phase is simply related to the storage cost.
The size of the challenge is
  $q * (8 + 48)$ bytes
The size of the proof is instead
  $s * 32 + 48$ bytes

# How to reproduce measurements

This could be scripted better, but for now:

```
git checkout 71a1dc6

make

# create example.txt file (set size in count)
dd if=/dev/random of=example.txt count=10k bs=1k

# edit parameters `s` and `q` in dagger/por/testpor.nim

# run the test
./env.sh nim c -r -d:danger dagger/por/testpor.nim
```

## Results

### Output format
```
File size=1048576 bytes, blocks=3383, sectors/block=10, sectorsize=31 bytes
CPU Time [Auth generation (s=10)] 1.258s
CPU Time [Generating challenge (q=80)] 0.027s
CPU Time [Issuing proof] 0.011s
CPU Time [Verifying proof] 0.023s
```

### MacBook Pro M1, single core

Results below are single shot, not averages ... treat them as such.

| Size[MB] | PoR "s"  | query size | setup[s]| proof[s] | verif[s] |
| -------- | -------- | --------   |------- | -----     | ------   |
|   1      |    10    |  80        |  1.25  | 0.011     |  0.023   |
|  10      |    10    |  80        | 12.24  | 0.012     |  0.024   |
| 100      |    10    |  80        |124.04  | 0.012     |  0.024   |
|          |          |            |        |           |          |
|  10      |     1    |  80        |118.51  | 0.011     |  0.023   |
|  10      |    10    |  80        | 12.24  | 0.011     |  0.023   |
|  10      |   100    |  80        |  1.70  | 0.022     |  0.035   |
|  10      |  1000    |  80        |  1.04  | 0.130     |  0.156   |
|          |          |            |        |           |          |
|  10      |   100    |  10        |  1.72  | 0.003     |  0.019   |
|  10      |   100    |  20        |  1.69  | 0.006     |  0.021   |
|  10      |   100    |  40        |  1.71  | 0.011     |  0.026   |
|  10      |   100    |  80        |  1.70  | 0.022     |  0.035   |
|  10      |   100    | 160        |  1.70  | 0.043     |  0.052   |

**Comment by cskiraly** [comment]
To put the numbers above in context and show the relation between operations in the above table, I add here the benchmark results from [nim-blscurve](https://github.com/status-im/nim-blscurve) on the same MacBook Pro M1.

```bash
nim-blscurve % benchmarks/bench_all 
Warmup: 1.0699 s, result 224 (displayed to avoid compiler optimizing warmup away)


Compiled with Clang
Optimization level => no optimization: false | release: true | danger: true

Backend: BLST, mode: 64-bit
====================================================================================================================================

Scalar multiplication G1 (255-bit, constant-time)                             12833.511 ops/s        77921 ns/op
Scalar multiplication G2 (255-bit, constant-time)                              5686.180 ops/s       175865 ns/op
EC add G1 (constant-time)                                                   1757469.244 ops/s          569 ns/op
EC add G2 (constant-time)                                                    672947.510 ops/s         1486 ns/op
------------------------------------------------------------------------------------------------------------------------------------
Pairing (Miller loop + Final Exponentiation)                                   1423.771 ops/s       702360 ns/op
------------------------------------------------------------------------------------------------------------------------------------
Hash to G2 (Draft #9) + affine conversion                                      6415.520 ops/s       155872 ns/op
------------------------------------------------------------------------------------------------------------------------------------
BLS signature                                                                  3026.955 ops/s       330365 ns/op
BLS verification                                                               1160.869 ops/s       861424 ns/op
BLS agg verif of 1 msg by 128 pubkeys                                          1098.072 ops/s       910687 ns/op
------------------------------------------------------------------------------------------------------------------------------------
BLS verif of 6 msgs by 6 pubkeys                                                195.255 ops/s      5121504 ns/op
Serial batch verify 6 msgs by 6 pubkeys (with blinding)                         343.634 ops/s      2910070 ns/op
Parallel batch verify of 6 msgs by 6 pubkeys (with blinding)                    674.070 ops/s      1483525 ns/op
------------------------------------------------------------------------------------------------------------------------------------
BLS verif of 60 msgs by 60 pubkeys                                               19.411 ops/s     51516979 ns/op
Serial batch verify 60 msgs by 60 pubkeys (with blinding)                        40.409 ops/s     24747250 ns/op
Parallel batch verify of 60 msgs by 60 pubkeys (with blinding)                  137.912 ops/s      7250987 ns/op
------------------------------------------------------------------------------------------------------------------------------------
BLS verif of 180 msgs by 180 pubkeys                                              6.379 ops/s    156764837 ns/op
Serial batch verify 180 msgs by 180 pubkeys (with blinding)                      13.418 ops/s     74524154 ns/op
Parallel batch verify of 180 msgs by 180 pubkeys (with blinding)                 46.878 ops/s     21331983 ns/op
------------------------------------------------------------------------------------------------------------------------------------

Using nthreads = 8. The number of threads can be changed with TP_NUM_THREADS environment variable.
```
